---
driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: true
  instance_type: t2.micro
  #Subnet
  subnet_id: subnet-018e9e3078d34571c
  associate_public_ip: true
  aws_ssh_key_id: ddn-eng-42

  transport:
    #use our key from machine to access the test machine
  #  ssh_key: ~/.ssh/ddn-eng-42.pem


# provisioner:
#   name: chef_zero
#   chef_licence: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    drive:
      box: ubuntu/xenial64

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
